global:
  resolve_timeout: 1m
receivers:
  - name: 'default'
    email_configs:
    - to: receivers@example.com
      smarthost: email.example.com:25
      from: admin@localhost
      send_resolved: true
      require_tls: true
    webhook_configs:
      - send_resolved: true
        url: http://slack.com/api

route:
  receiver: default
  routes: 
  - match:
      severity: critical
    receiver: 'default'
    group_by: ['nodes']
    group_interval: 10m
    group_wait: 1m
    repeat_interval: 2h